version: "3.0"
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: fylder-jenkins
    restart: always
    ports:
      - "8201:8080"
      - "50000:50000"
    user: root
    environment:
      JAVA_OPTS: "-Djava.util.logging.config.file=/var/jenkins_home/log.properties"
    volumes:
      - ./data/jenkins/:/var/jenkins_home
